import logging

logging.basicConfig(
    format="%(levelname)-8s %(module)-14s %(message)s", level=logging.INFO
)
log = logging.getLogger(__name__)

import h5py as h5
import numpy as np
import torch

from .kinds import Compartments
from torchdiffeq import odeint

log = logging.getLogger(__name__)

def apolo_model_7(t, y, params):
        """ODE system for the Dengue model
        Args:
            t: Time point
            y: State vector [Ms, Me, Mi, Hs, He, Hi, Hr, Itot]
            parameters: Dictionary containing model parameters
        """
        # Ms, Me, Mi, Hs, He, Hi, Hr, Itot = y
        Itot, Hi, Me, Hr, Hs, He, Ms, Mi = y
        lambda_, beta_m, mu_m, theta_m, mu_h, beta_h, theta_h, gamma_h = params
    
        # Calculate total populations
        H = Hr + Hs + He + Hi  # Total human population
        M = Me + Ms + Mi       # Total mosquito population
    
        # Ensure populations are not zero
        H = torch.clamp(H, min=1e-8)
        M = torch.clamp(M, min=1e-8)
    
        # ODE system
        dydt = torch.stack([
            theta_h * He,
            theta_h * He - (gamma_h + mu_h) * Hi,
            beta_m * Hi * Ms / H - (theta_m + mu_m) * Me,
            gamma_h * Hi - mu_h * Hr,
            mu_h * H - beta_h * Mi * Hs / M - mu_h * Hs,
            beta_h * Mi * Hs / M - (theta_h + mu_h) * He,
            lambda_ - beta_m * Hi * Ms / H - mu_m * Ms,
            theta_m * Me - mu_m * Mi,
        ])
        
        return dydt

def generate_smooth_data(
    cfg, *, parameters=None, init_state: torch.tensor = None
) -> torch.Tensor:
    """Generates a dataset of counts for each compartment by iteratively solving the system of differential equations.

    :param cfg: configuration file, containing parameter values (possibly as a ``Sequence``, if time-dependent),
        number of steps, burn-in period, etc.
    :param parameters: (optional) parameters used to override cfg settings
    :param init_state: (optional) initial state to use; defaults to a generic density if ``None``
    :return: ``torch.Tensor`` training dataset, with the burn-in period discarded
    """

    # Get config settings
    num_steps: int = cfg["num_steps"]
    burn_in: int = cfg.get("burn_in", 0)
    dt: float = cfg["dt"]
    device = torch.device('cpu')

    # Initial param's input "to_learn": [Ms0, Me0, ..., beta_h, beta_m, gamma_h, lambda, mu_m, theta_h, theta_m] of ODE
    Itot0 = torch.tensor(12, dtype=torch.float32)
    y0 = (
        torch.tensor((Itot0, cfg["Hi0"], cfg["Me0"], 
                     cfg["Hr0"], cfg["Hs0"], 
                     cfg["He0"], cfg["Ms0"], 
                     cfg["Mi0"]),dtype=torch.float32)
        if parameters is None
        else torch.tensor((Itot0, parameters["Hi0"], parameters["Me0"], 
                          parameters["Hr0"], parameters["Hs0"], 
                          parameters["He0"], parameters["Ms0"], 
                          parameters["Mi0"]),dtype=torch.float32)
    ).to(device)
    params = (
        torch.tensor((cfg['lambda'], cfg['beta_m'], 
                     cfg['mu_m'], cfg['theta_m'], 
                     0.0004, cfg['beta_h'],
                     cfg['theta_h'], cfg['gamma_h']), dtype=torch.float32)
        if parameters is None
        else torch.tensor((parameters["lambda"], parameters["beta_m"], 
                          parameters["mu_m"], parameters["theta_m"], 
                          0.0004, parameters["beta_h"], 
                          parameters["theta_h"], parameters['gamma_h']),dtype=torch.float32)
    ).to(device)

    # Solve ODE system
    t_true = torch.arange(0, num_steps + burn_in, dtype=torch.float32)
    solution = odeint(func=lambda y, t: apolo_model_7(y, t, params), 
                      y0=y0, t=t_true,
                      method='dopri5',     # dopri5, euler, or rk4
                      rtol=1e-3,          # Relaxed tolerance
                      atol=1e-6,          # Relaxed absolute tolerance
                      )
    while torch.isnan(solution).any() or torch.isinf(solution).any():
        solution = odeint(func=lambda y, t: apolo_model_7(y, t, params), 
                          y0=y0, t=t_true,
                          method='euler',     # dopri5, euler, or rk4
                          rtol=1e-3,          # Relaxed tolerance
                          atol=1e-6,          # Relaxed absolute tolerance
                          )

    # Ensure non-negative values & discard the burn-in, if specified
    return torch.abs(solution[burn_in:]).unsqueeze(dim=-1)  # (batch_size, #_latent_var)

def get_data(data_cfg: dict, h5group: h5.Group) -> torch.Tensor:
    """Returns the training data for the Dengue model. If a directory is passed, the data is loaded from that directory.
    Otherwise, synthetic training data is generated by iteratively solving the ODE system.

    :param data_cfg: configuration file
    :param h5group: hdf5.group to which to write the data
    :return: ``torch.Tensor`` training data
    """

    # Load training data from file
    if "load_from_dir" in data_cfg.keys():
        log.info("   Loading training data ...")
        # Load training data from hdf5 file
        with h5.File(data_cfg["load_from_dir"], "r") as f:
            training_data = torch.from_numpy(
                np.array(f["Dengue"]["true_counts"])
            ).float()

    # Generate synthetic data
    elif "synthetic_data" in data_cfg.keys():
        log.info("   Generating training data ...")

        # Generate training data by integrating the model ODE equations
        training_data = generate_smooth_data(data_cfg["synthetic_data"])
        
        # Log normalisation
        epsilon = 1e-6
        training_data = np.log(training_data + epsilon)  # log1p = log(1 + x)

    else:
        raise ValueError(
            f"You must supply one of 'load_from_dir' or 'synthetic data' keys!"
        )

    # Save training data to hdf5 dataset and return
    dset_true_counts = h5group.create_dataset(
        "true_counts",
        training_data.shape,
        maxshape=training_data.shape,
        chunks=True,
        compression=3,
        dtype=float,
    )

    dset_true_counts.attrs["dim_names"] = ["time", "kind", "dim_name__0"]
    dset_true_counts.attrs["coords_mode__time"] = "trivial"
    dset_true_counts.attrs["coords_mode__kind"] = "values"
    dset_true_counts.attrs["coords__kind"] = [k.name for k in Compartments]
    dset_true_counts.attrs["coords_mode__dim_name__0"] = "trivial"

    dset_true_counts[:, :, :] = training_data

    return training_data
